In [37]:
import cv2
import numpy as np

thresh = 127
def read_image_to_binary(name,thresh):
    gray = cv2.imread(f"calibration_images/{name}.png",cv2.IMREAD_GRAYSCALE)
    return cv2.threshold(gray, thresh, 255, cv2.THRESH_BINARY)[1]

def show_image(img):
    cv2.namedWindow("img",cv2.WINDOW_NORMAL)
    cv2.resizeWindow("img",400,400)
    cv2.imshow("img",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


img_1 = read_image_to_binary("1",80)
#img_1 = img_1[400:1000,700:1850]

img_2 = read_image_to_binary("2",80)
img_3 = read_image_to_binary("3",80)


In [38]:
img_list = [img_1, img_2, img_3]

In [42]:
# Prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
object_points = np.zeros((10 * 15, 3), np.float32)
object_points[:, :2] = np.mgrid[0:15, 0:10].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
obj_points = []  # 3D points in real world space
img_points = []  # 2D points in image plane.

# Iterate through images and find chessboard corners
for img in img_list:  # Assuming you have 20 images named as 1.jpg, 2.jpg, ..., 20.jpg

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(img, (15, 10), None)

    # If found, add object points, image points
    if ret:
        obj_points.append(object_points)
        img_points.append(corners)

        # Draw and display the corners
        cv2.drawChessboardCorners(img, (15, 10), corners, ret)
        cv2.namedWindow("Chessboard Corners", cv2.WINDOW_NORMAL)
        cv2.resizeWindow("Chessboard Corners",700,700)
        cv2.imshow('Chessboard Corners', img)
        cv2.waitKey(0)  # Wait for a while to visualize the images
    print(ret)

cv2.destroyAllWindows()

# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, img_1.shape[::-1], None, None)

# Print the camera matrix and distortion coefficients
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)


True
True
True
Camera Matrix:
[[1.95991862e+03 0.00000000e+00 1.33725664e+03]
 [0.00000000e+00 1.95234744e+03 1.10168466e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion Coefficients:
[[-0.25286984  0.32644042 -0.01672609 -0.00368907 -0.44213302]]
