In [6]:
import cv2
import numpy as np
import os
from PIL import Image, ImageFilter

thresh = 80
def load_images_from_folder(folder=str,thresh=int,filter=bool):
    images = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder,filename),cv2.IMREAD_GRAYSCALE)
        img = cv2.threshold(img, thresh, 255, cv2.THRESH_BINARY)[1]
        if filter:
            img = Image.fromarray(img)
            img = img.filter(ImageFilter.MedianFilter(size=9))
            img = np.array(img)
        images.append(img)
    return images

images = load_images_from_folder("calibration_images", thresh, True)

def show_image(img):
    cv2.namedWindow("img",cv2.WINDOW_NORMAL)
    cv2.resizeWindow("img",400,400)
    cv2.imshow("img",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

for img in images:
    show_image(img)

In [7]:
# Prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
object_points = np.zeros((10 * 15, 3), np.float32)
object_points[:, :2] = np.mgrid[0:15, 0:10].T.reshape(-1, 2)

# Arrays to store object points and image points from all images
obj_points = []  # 3D points in real world space
img_points = []  # 2D points in image plane.

# Iterate through images and find chessboard corners
for img in images:  # Assuming you have 20 images named as 1.jpg, 2.jpg, ..., 20.jpg

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(img, (15, 10), None)

    # If found, add object points, image points
    if ret:
        obj_points.append(object_points)
        img_points.append(corners)

        # Draw and display the corners
        cv2.drawChessboardCorners(img, (15, 10), corners, ret)
        cv2.namedWindow("Chessboard Corners", cv2.WINDOW_NORMAL)
        cv2.resizeWindow("Chessboard Corners",700,700)
        cv2.imshow('Chessboard Corners', img)
        cv2.waitKey(0)  # Wait for a while to visualize the images
    print(ret)

cv2.destroyAllWindows()

# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, images[0].shape[::-1], None, None)

# Print the camera matrix and distortion coefficients
print("Camera Matrix:")
print(mtx)
print("\nDistortion Coefficients:")
print(dist)


True
False
True
True
True
True
True
True
True
True
Camera Matrix:
[[2.66687242e+03 0.00000000e+00 1.29587472e+03]
 [0.00000000e+00 2.66083170e+03 1.02231091e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion Coefficients:
[[-4.63938658e-01  1.17095684e+00 -7.48369194e-03  1.84250311e-03
  -2.89898607e+00]]
